/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AppController_getHello"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Buscar lista de todos os usuários */
        get: operations["UsersController_findAllUsers"];
        put?: never;
        /** Criar um novo usuário */
        post: operations["UsersController_createUser"];
        delete?: never;
        options?: never;
        head?: never;
        /** Atualizar a senha de um usuário autenticado */
        patch: operations["UsersController_updateUserPassword"];
        trace?: never;
    };
    "/users/{username}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Buscar usuário através do username */
        get: operations["UsersController_findOneByUsername"];
        put?: never;
        post?: never;
        /** Deleta um usuário cadastrado permanentemente */
        delete: operations["UsersController_deleteUser"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{username}/roles/{roleId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Adicionar uma Role específica ao usuário */
        post: operations["UsersController_addRoleToUser"];
        /** Remover uma Role específica do usuário */
        delete: operations["UsersController_removeRoleFromUser"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar todas as Roles do tenant com paginação */
        get: operations["RolesController_findAllRoles"];
        put?: never;
        /** Criar uma nova Role no tenant */
        post: operations["RolesController_createRole"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/roles/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Buscar uma Role por ID */
        get: operations["RolesController_findRoleById"];
        put?: never;
        post?: never;
        /** Deletar uma Role */
        delete: operations["RolesController_deleteRole"];
        options?: never;
        head?: never;
        /** Atualizar permissões/nome de uma Role */
        patch: operations["RolesController_updateRole"];
        trace?: never;
    };
    "/auth": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Realiza a autenticação do usuário */
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Renova os tokens de acesso a partir do cookie de refresh */
        post: operations["AuthController_refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Invalida a sessão removendo os cookies de autenticação e revogando o token */
        post: operations["AuthController_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista os produtos do tenant com paginação */
        get: operations["ProductsController_findAllProducts"];
        put?: never;
        /** Cadastra um novo produto (Cadastro Rápido) */
        post: operations["ProductsController_createProduct"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Atualiza um produto ou vincula dados adicionais (Ex: Categoria) */
        patch: operations["ProductsController_updateProduct"];
        trace?: never;
    };
    "/products/{sku}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Busca um produto pelo SKU */
        get: operations["ProductsController_findOneBySku"];
        put?: never;
        post?: never;
        /** Remove um produto pelo SKU */
        delete: operations["ProductsController_deleteProduct"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista todas as categorias do tenant */
        get: operations["CategoriesController_findAllCategories"];
        put?: never;
        /** Cria uma nova categoria */
        post: operations["CategoriesController_createCategory"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/categories/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Busca uma categoria pelo nome */
        get: operations["CategoriesController_findByCategoryName"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/categories/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove uma categoria pelo ID */
        delete: operations["CategoriesController_deleteCategory"];
        options?: never;
        head?: never;
        /** Atualiza uma categoria existente pelo ID */
        patch: operations["CategoriesController_updateCategory"];
        trace?: never;
    };
    "/locations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar todas as localizações
         * @description Retorna uma lista paginada de localizações.
         */
        get: operations["LocationsController_findAllLocations"];
        put?: never;
        /**
         * Criar localização
         * @description Cria uma nova localização para o tenant logado.
         */
        post: operations["LocationsController_createLocation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/locations/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Buscar localização por código
         * @description Busca uma localização pelo código informado.
         */
        get: operations["LocationsController_findByCode"];
        put?: never;
        post?: never;
        /**
         * Deletar localização
         * @description Remove uma localização pelo código fornecido.
         */
        delete: operations["LocationsController_deleteLocation"];
        options?: never;
        head?: never;
        /**
         * Atualizar localização
         * @description Atualiza parcialmente os campos de uma localização existente.
         */
        patch: operations["LocationsController_updateLocation"];
        trace?: never;
    };
    "/movements/product/{productId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar movimentações por produto
         * @description Retorna o histórico paginado de movimentações de um produto específico.
         */
        get: operations["MovementsController_findAllPaginatedByProduct"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/movements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Registra movimentação de entrada/saída geral
         * @description Registra uma entrada ou saída no saldo do produto e atualiza o histórico.
         */
        post: operations["MovementsController_registerMovement"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/movements/allocate-location": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Aloca ou transfere produtos entre posições físicas
         * @description Aloca produtos do saldo geral para uma posição física ou realiza transferência entre posições.
         */
        post: operations["MovementsController_allocateLocation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CreateUserDto: {
            /** @example edilson.segundo */
            username: string;
            /**
             * @description Array de UUIDs das Roles atribuídas ao usuário
             * @example [
             *       "c22e5a7d-b2b2-4d76-8809-51a81231f24d"
             *     ]
             */
            roleIds: string[];
        };
        UpdatePasswordDto: {
            /**
             * @description Id da empresa no qual o usuário pertence
             * @example uuid
             */
            tenantId: string;
            /**
             * @description Nome do usuário deve está no formato: nome.sobrenome
             * @example edilson.segundo
             */
            username: string;
            /** @description Deve está true quando a senha temporária for gerada */
            mustChangePassword: boolean;
            /**
             * @description Senha definitiva do usuário. Deve ser passada apenas após o primeiro do usuário ou no primeiro login após redifinição de senha.
             * @example 12345678
             */
            password: string;
        };
        RoleDto: {
            /** @example Operador de Estoque */
            name: string;
            /**
             * @example [
             *       "products.read",
             *       "roles.create"
             *     ]
             */
            permissions: ("users.create" | "users.read" | "users.update" | "users.delete" | "products.create" | "products.read" | "products.update" | "products.delete" | "categories.create" | "categories.read" | "categories.update" | "categories.delete" | "roles.create" | "roles.read" | "roles.update" | "roles.delete" | "locations.create" | "locations.read" | "locations.update" | "locations.delete" | "movement.register" | "movement.allocate" | "movement.read")[];
        };
        UpdateRoleDto: {
            /** @example Operador de Estoque */
            name?: string;
            /**
             * @example [
             *       "products.read",
             *       "roles.create"
             *     ]
             */
            permissions?: ("users.create" | "users.read" | "users.update" | "users.delete" | "products.create" | "products.read" | "products.update" | "products.delete" | "categories.create" | "categories.read" | "categories.update" | "categories.delete" | "roles.create" | "roles.read" | "roles.update" | "roles.delete" | "locations.create" | "locations.read" | "locations.update" | "locations.delete" | "movement.register" | "movement.allocate" | "movement.read")[];
        };
        LoginDto: {
            /** @example segundo */
            username: string;
            /** @example 12345678 */
            password: string;
        };
        ProductDto: {
            /**
             * @description Código SKU único do produto
             * @example PROD-ALFA-001
             */
            sku: string;
            /**
             * @description Nome comercial do produto
             * @example Refrigerante Cola 350ml
             */
            name: string;
            /**
             * @description Preço de venda do produto
             * @example 5.5
             */
            price: number;
            /**
             * @description Preço de custo do produto
             * @example 2.8
             */
            costPrice: number;
            /**
             * @description Estoque mínimo de segurança
             * @example 10
             */
            minimumStock: number;
            /**
             * @description Unidade de Medida (UOM)
             * @default UN
             * @example UN
             */
            uom: string;
            /**
             * @description Código de barras EAN/GTIN (EAN-8 a EAN-14)
             * @example 7891234567890
             */
            ean?: Record<string, never> | null;
            /**
             * @description Nomenclatura Comum do Mercosul (NCM)
             * @example 22021000
             */
            ncm?: Record<string, never> | null;
            /**
             * @description Especificação da Substituição Tributária (CEST)
             * @example 0300700
             */
            cest?: Record<string, never> | null;
            /**
             * @description Origem da mercadoria (Ex: 0 para Nacional)
             * @default 0
             * @example 0
             */
            origin: string;
            /**
             * @description Código de Situação da Operação no Simples Nacional (CSOSN)
             * @example 102
             */
            csosn?: Record<string, never> | null;
            /**
             * @description Código de Situação Tributária (CST)
             * @example null
             */
            cst?: Record<string, never> | null;
        };
        UpdateProductDto: {
            /**
             * @description Código SKU único do produto
             * @example PROD-ALFA-001
             */
            sku?: string;
            /**
             * @description Nome comercial do produto
             * @example Refrigerante Cola 350ml
             */
            name?: string;
            /**
             * @description Preço de venda do produto
             * @example 5.5
             */
            price?: number;
            /**
             * @description Preço de custo do produto
             * @example 2.8
             */
            costPrice?: number;
            /**
             * @description Estoque mínimo de segurança
             * @example 10
             */
            minimumStock?: number;
            /**
             * @description Unidade de Medida (UOM)
             * @default UN
             * @example UN
             */
            uom: string;
            /**
             * @description Código de barras EAN/GTIN (EAN-8 a EAN-14)
             * @example 7891234567890
             */
            ean?: Record<string, never> | null;
            /**
             * @description Nomenclatura Comum do Mercosul (NCM)
             * @example 22021000
             */
            ncm?: Record<string, never> | null;
            /**
             * @description Especificação da Substituição Tributária (CEST)
             * @example 0300700
             */
            cest?: Record<string, never> | null;
            /**
             * @description Origem da mercadoria (Ex: 0 para Nacional)
             * @default 0
             * @example 0
             */
            origin: string;
            /**
             * @description Código de Situação da Operação no Simples Nacional (CSOSN)
             * @example 102
             */
            csosn?: Record<string, never> | null;
            /**
             * @description Código de Situação Tributária (CST)
             * @example null
             */
            cst?: Record<string, never> | null;
            /**
             * @description UUID da categoria associada ao produto
             * @example d3b07384-d113-4ec6-a5d6-c1c234567890
             */
            categoryId?: Record<string, never> | null;
        };
        Location: {
            /**
             * @description Identificador único da localização (UUID v4)
             * @example f21a48c9-598d-4a14-8789-08226edb3b0d
             */
            id: string;
            /**
             * @description Identificador do tenant proprietário
             * @example tenant-12345
             */
            tenantId: string;
            /**
             * @description Código/Endereço físico da localização no estoque
             * @example CORREDOR-A-PRATELEIRA-02
             */
            code: string;
            /**
             * @description Tipo da localização (DISPLAY: Mostruário/Área de venda, STORAGE: Depósito/Estoque)
             * @default STORAGE
             * @example STORAGE
             * @enum {string}
             */
            type: "DISPLAY" | "STORAGE";
            /**
             * @description Capacidade máxima suportada por esta posição (opcional)
             * @example 100
             */
            capacity?: number | null;
            /**
             * @description Descrição opcional ou observações sobre a localização
             * @example Área refrigerada para produtos perecíveis
             */
            description?: Record<string, never> | null;
            /** @description Produtos e quantidades armazenadas nesta localização */
            productLocations?: components["schemas"]["ProductLocation"][];
            /**
             * Format: date-time
             * @description Data de criação da localização
             * @example 2026-07-27T20:00:00.000Z
             */
            createdAt: string;
            /**
             * Format: date-time
             * @description Data da última atualização da localização
             * @example 2026-07-27T20:00:00.000Z
             */
            updatedAt: string;
        };
        ProductLocation: {
            /**
             * @description Identificador único do vínculo (UUID v4)
             * @example f21a48c9-598d-4a14-8789-08226edb3b0d
             */
            id: string;
            /**
             * @description Identificador do tenant proprietário
             * @example tenant-12345
             */
            tenantId: string;
            /**
             * @description ID do produto vinculado
             * @example d3b07384-d113-424a-a1d2-06834d858348
             */
            productId: string;
            /** @description Produto vinculado */
            product?: components["schemas"]["Product"];
            /**
             * @description ID da localização vinculada
             * @example f21a48c9-598d-4a14-8789-08226edb3b0d
             */
            locationId: string;
            /** @description Localização vinculada */
            location?: components["schemas"]["Location"];
            /**
             * @description Quantidade estocada deste produto nesta localização específica
             * @default 0
             * @example 50
             */
            quantity: number;
            /**
             * Format: date-time
             * @description Data de vínculo do produto à localização
             * @example 2026-07-27T20:00:00.000Z
             */
            createdAt: string;
            /**
             * Format: date-time
             * @description Data da última atualização de quantidade
             * @example 2026-07-27T20:00:00.000Z
             */
            updatedAt: string;
        };
        Product: {
            /**
             * @description Identificador único do produto (UUID v4)
             * @example d3b07384-d113-424a-a1d2-06834d858348
             */
            id: string;
            /**
             * @description Identificador do tenant proprietário
             * @example tenant-12345
             */
            tenantId: string;
            /**
             * @description Código SKU (Stock Keeping Unit) do produto
             * @example CAM-ALGODAO-M
             */
            sku: string;
            /**
             * @description Nome do produto
             * @example Camiseta de Algodão M
             */
            name: string;
            /**
             * @description Unidade de medida do produto
             * @default UN
             * @example UN
             */
            uom: string;
            /**
             * @description Quantidade em estoque total do produto (soma de todas as localizações)
             * @default 0
             * @example 150
             */
            currentStock: number;
            /**
             * @description Estoque mínimo de alerta para reposição
             * @default 0
             * @example 10
             */
            minimumStock: number;
            /**
             * @description Preço de venda do produto
             * @default 0
             * @example 49.9
             */
            price: number;
            /**
             * @description Preço de custo do produto
             * @default 0
             * @example 20
             */
            costPrice: number;
            /**
             * @description ID da categoria à qual o produto pertence
             * @example a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11
             */
            categoryId?: Record<string, never> | null;
            /** @description Categoria vinculada ao produto */
            category?: components["schemas"]["Category"] | null;
            /** @description Distribuição do produto nas localizações do estoque */
            locations?: components["schemas"]["ProductLocation"][];
            /**
             * @description Código EAN / GTIN (Código de barras)
             * @example 7891234567890
             */
            ean?: Record<string, never> | null;
            /**
             * @description Código NCM (Nomenclatura Comum do Mercosul)
             * @example 61091000
             */
            ncm?: Record<string, never> | null;
            /**
             * @description Código CEST (Especificação da Substituição Tributária)
             * @example 2803800
             */
            cest?: Record<string, never> | null;
            /**
             * @description Origem da mercadoria (0 - Nacional, 1 - Estrangeira, etc.)
             * @default 0
             * @example 0
             */
            origin: string;
            /**
             * @description Código CSOSN (Simples Nacional)
             * @example 102
             */
            csosn?: Record<string, never> | null;
            /**
             * @description Código CST (Regime Normal)
             * @example 00
             */
            cst?: Record<string, never> | null;
            /**
             * @description Identificador do usuário que criou o registro
             * @example admin@empresa.com
             */
            createdBy?: string;
            /**
             * Format: date-time
             * @description Data de criação do registro
             * @example 2026-07-27T20:00:00.000Z
             */
            createdAt: string;
            /**
             * Format: date-time
             * @description Data da última atualização do registro
             * @example 2026-07-27T20:00:00.000Z
             */
            updatedAt: string;
            /**
             * @description Identificador do usuário que fez a última atualização
             * @example admin@empresa.com
             */
            updatedBy?: string;
        };
        Category: {
            /**
             * @description Identificador único da categoria (UUID v4)
             * @example a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11
             */
            id: string;
            /**
             * @description Identificador do tenant proprietário
             * @example tenant-12345
             */
            tenantId: string;
            /**
             * @description Nome da categoria
             * @example Eletrônicos
             */
            name: string;
            /**
             * @description Descrição da categoria
             * @example Dispositivos eletrônicos e acessórios
             */
            description?: Record<string, never> | null;
            /**
             * @description Indica se a categoria está ativa
             * @example true
             */
            isActive: boolean;
            /** @description Lista de produtos pertencentes a esta categoria */
            products?: components["schemas"]["Product"][];
            /**
             * Format: date-time
             * @description Data de criação do registro
             * @example 2026-07-27T20:00:00.000Z
             */
            createdAt: string;
            /**
             * Format: date-time
             * @description Data da última atualização do registro
             * @example 2026-07-27T20:00:00.000Z
             */
            updatedAt: string;
        };
        CategoryDto: {
            /**
             * @description Nome único da categoria dentro do tenant
             * @example Eletrônicos
             */
            name: string;
            /**
             * @description Descrição detalhada da categoria
             * @example Dispositivos eletrônicos e acessórios em geral
             */
            description?: Record<string, never> | null;
            /**
             * @description Status de ativação da categoria
             * @default true
             * @example true
             */
            isActive: boolean;
        };
        UpdateCategoryDto: {
            /**
             * @description Nome único da categoria dentro do tenant
             * @example Eletrônicos
             */
            name?: string;
            /**
             * @description Descrição detalhada da categoria
             * @example Dispositivos eletrônicos e acessórios em geral
             */
            description?: Record<string, never> | null;
            /**
             * @description Status de ativação da categoria
             * @default true
             * @example true
             */
            isActive: boolean;
        };
        LocationDto: {
            /**
             * @description Código ou endereço físico da localização no estoque
             * @example CORREDOR-A-PRATELEIRA-02
             */
            code: string;
            /**
             * @description Tipo da localização (DISPLAY ou STORAGE)
             * @default STORAGE
             * @example STORAGE
             * @enum {string}
             */
            type: "DISPLAY" | "STORAGE";
            /**
             * @description Capacidade máxima suportada por esta posição (opcional para STORAGE, recomendada para DISPLAY)
             * @example 100
             */
            capacity?: number | null;
            /**
             * @description Descrição opcional ou observações sobre a localização
             * @example Área refrigerada para produtos perecíveis
             */
            description?: Record<string, never> | null;
        };
        UpdateLocationDto: {
            /**
             * @description Código ou endereço físico da localização no estoque
             * @example CORREDOR-A-PRATELEIRA-02
             */
            code?: string;
            /**
             * @description Tipo da localização (DISPLAY ou STORAGE)
             * @default STORAGE
             * @example STORAGE
             * @enum {string}
             */
            type: "DISPLAY" | "STORAGE";
            /**
             * @description Capacidade máxima suportada por esta posição (opcional para STORAGE, recomendada para DISPLAY)
             * @example 100
             */
            capacity?: number | null;
            /**
             * @description Descrição opcional ou observações sobre a localização
             * @example Área refrigerada para produtos perecíveis
             */
            description?: Record<string, never> | null;
        };
        MovementDto: {
            /**
             * @description Tipo da movimentação
             * @enum {string}
             */
            typeMovement: "IN" | "OUT" | "TRANSFER";
            /**
             * @description Quantidade movimentada
             * @example 10
             */
            quantity: number;
            /** @description Motivo da movimentação */
            reason?: string;
            /** @description ID do produto (UUID v4) */
            productId: string;
            /** @description ID da localização (UUID v4) */
            locationId?: string;
        };
        AllocateLocationDto: {
            /** @description ID do produto */
            productId: string;
            /** @description ID da posição de destino */
            targetLocationId: string;
            /** @description ID da posição de origem (se for transferência) */
            sourceLocationId?: string;
            /** @description Quantidade a ser movimentada */
            quantity: number;
            /** @description Motivo da movimentação */
            reason?: string;
        };
        /**
         * @description Lista completa de permissões disponíveis no sistema
         * @enum {string}
         */
        EPermission: "users.create" | "users.read" | "users.update" | "users.delete" | "products.create" | "products.read" | "products.update" | "products.delete" | "categories.create" | "categories.read" | "categories.update" | "categories.delete" | "roles.create" | "roles.read" | "roles.update" | "roles.delete" | "locations.create" | "locations.read" | "locations.update" | "locations.delete" | "movement.register" | "movement.allocate" | "movement.read";
        PermissionsMetadataDto: {
            /**
             * @description Lista completa de permissões disponíveis no sistema
             * @example [
             *       "users.create",
             *       "users.read",
             *       "users.update",
             *       "users.delete",
             *       "products.create",
             *       "products.read",
             *       "products.update",
             *       "products.delete",
             *       "categories.create",
             *       "categories.read",
             *       "categories.update",
             *       "categories.delete",
             *       "roles.create",
             *       "roles.read",
             *       "roles.update",
             *       "roles.delete",
             *       "locations.create",
             *       "locations.read",
             *       "locations.update",
             *       "locations.delete",
             *       "movement.register",
             *       "movement.allocate",
             *       "movement.read"
             *     ]
             */
            permissions: components["schemas"]["EPermission"][];
            /**
             * @description Nome base da role de administrador do sistema
             * @example Admin
             */
            systemAdminRole: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AppController_getHello: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_findAllUsers: {
        parameters: {
            query?: {
                /** @description Número da página (mínimo: 1) */
                page?: number;
                /** @description Quantidade de itens por página (mínimo: 1, máximo: 100) */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Retorna uma mensagem de status, os dados parciais paginados e metadados de paginação. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Não autorizado. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Nenhum usuário cadastrado no sistema. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_createUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserDto"];
            };
        };
        responses: {
            /** @description Usuário cadastrado com sucesso! */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Dados de validação inválidos. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Token de acesso inválido ou ausente. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Acesso negado: permissão insuficiente. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_updateUserPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePasswordDto"];
            };
        };
        responses: {
            /** @description Senha de usuário atualizada com sucesso! */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Senha atual incorreta ou nova senha inválida. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Não autorizado. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_findOneByUsername: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description O username único do usuário */
                username: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Retorna uma mensagem de status e os dados parciais do usuário encontrado. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Não autorizado. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Usuário não encontrado. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_deleteUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description O username do usuário a ser deletado */
                username: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Usuário deletado com sucesso do banco de dados. Sem conteúdo de retorno. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Não autorizado. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Acesso negado: permissão insuficiente. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Usuário não encontrado. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_addRoleToUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                username: string;
                roleId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_removeRoleFromUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                username: string;
                roleId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RolesController_findAllRoles: {
        parameters: {
            query?: {
                /** @description Número da página (mínimo: 1) */
                page?: number;
                /** @description Quantidade de itens por página (mínimo: 1, máximo: 100) */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RolesController_createRole: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoleDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RolesController_findRoleById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RolesController_deleteRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RolesController_updateRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateRoleDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_login: {
        parameters: {
            query?: never;
            header: {
                /** @description ID único do hardware do dispositivo móvel (Flutter) */
                "x-device-id"?: string;
                /** @description Slug do tenant extraído do subdomínio */
                "x-tenant-slug": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            /** @description Login efetuado com sucesso e tokens gerados. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Senha incorreta ou cabeçalho x-tenant-slug ausente. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Usuário não encontrado. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_refresh: {
        parameters: {
            query?: never;
            header?: {
                /** @description ID único do hardware do dispositivo móvel (Flutter) */
                "x-device-id"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tokens renovados com sucesso. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Refresh token inválido, expirado ou dispositivo divergente. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logout realizado com sucesso. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Não autorizado. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProductsController_findAllProducts: {
        parameters: {
            query?: {
                /** @description Número da página (mínimo: 1) */
                page?: number;
                /** @description Quantidade de itens por página (mínimo: 1, máximo: 100) */
                limit?: number;
            };
            header: {
                /** @description Identificador do Tenant */
                "x-tenant-id": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista paginada de produtos retornada com sucesso. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Nenhum produto encontrado para este tenant. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProductsController_createProduct: {
        parameters: {
            query?: never;
            header: {
                /** @description Identificador do Tenant */
                "x-tenant-id": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductDto"];
            };
        };
        responses: {
            /** @description Produto criado com sucesso. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Dados de requisição inválidos. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Produto com este SKU já existe no tenant. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProductsController_updateProduct: {
        parameters: {
            query?: never;
            header: {
                /** @description Identificador do Tenant */
                "x-tenant-id": string;
            };
            path: {
                /** @description UUID do produto a ser atualizado */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProductDto"];
            };
        };
        responses: {
            /** @description Produto atualizado com sucesso. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Produto não encontrado. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProductsController_findOneBySku: {
        parameters: {
            query?: never;
            header: {
                /** @description Identificador do Tenant */
                "x-tenant-id": string;
            };
            path: {
                /** @description Código SKU do produto */
                sku: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Produto localizado. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Product"];
                };
            };
            /** @description Produto não encontrado. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProductsController_deleteProduct: {
        parameters: {
            query?: never;
            header: {
                /** @description Identificador do Tenant */
                "x-tenant-id": string;
            };
            path: {
                /** @description Código SKU do produto a ser removido */
                sku: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Produto removido com sucesso. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Produto não encontrado. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CategoriesController_findAllCategories: {
        parameters: {
            query?: {
                /** @description Número da página (mínimo: 1) */
                page?: number;
                /** @description Quantidade de itens por página (mínimo: 1, máximo: 100) */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista de categorias retornada com sucesso. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"][];
                };
            };
            /** @description Não autorizado. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Acesso negado (requer privilégios de administrador). */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Nenhuma categoria encontrada para este tenant. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CategoriesController_createCategory: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryDto"];
            };
        };
        responses: {
            /** @description Categoria criada com sucesso. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Dados de entrada inválidos. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Não autorizado. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Acesso negado (requer privilégios de administrador). */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Já existe uma categoria com esse nome para o tenant. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CategoriesController_findByCategoryName: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Nome da categoria a ser buscada */
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Categoria encontrada. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"];
                };
            };
            /** @description Não autorizado. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Acesso negado (requer privilégios de administrador). */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Categoria não encontrada. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CategoriesController_deleteCategory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID da categoria a ser removida (UUID) */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Categoria removida com sucesso. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Não autorizado. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Acesso negado (requer privilégios de administrador). */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Categoria não encontrada. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CategoriesController_updateCategory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID da categoria (UUID) */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCategoryDto"];
            };
        };
        responses: {
            /** @description Categoria atualizada com sucesso. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Dados de entrada inválidos. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Não autorizado. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Acesso negado (requer privilégios de administrador). */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Categoria não encontrada. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    LocationsController_findAllLocations: {
        parameters: {
            query?: {
                /** @description Número da página (mínimo: 1) */
                page?: number;
                /** @description Quantidade de itens por página (mínimo: 1, máximo: 100) */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista de localizações retornada. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Token de acesso inválido ou expirado. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Acesso negado: permissão insuficiente. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Nenhuma localização encontrada. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    LocationsController_createLocation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LocationDto"];
            };
        };
        responses: {
            /** @description Localização criada com sucesso. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Dados informados inválidos. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Token de acesso inválido ou expirado. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Acesso negado: permissão insuficiente. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    LocationsController_findByCode: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Código da localização */
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Localização encontrada. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Token de acesso inválido ou expirado. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Acesso negado: permissão insuficiente. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Localização não encontrada. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    LocationsController_deleteLocation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Código da localização */
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Localização deletada com sucesso. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Token de acesso inválido ou expirado. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Acesso negado: permissão insuficiente. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Localização não encontrada. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    LocationsController_updateLocation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Código atual da localização */
                code: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateLocationDto"];
            };
        };
        responses: {
            /** @description Localização atualizada com sucesso. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Dados informados inválidos. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Token de acesso inválido ou expirado. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Acesso negado: permissão insuficiente. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Localização não encontrada. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MovementsController_findAllPaginatedByProduct: {
        parameters: {
            query?: {
                /** @description Número da página (mínimo: 1) */
                page?: number;
                /** @description Quantidade de itens por página (mínimo: 1, máximo: 100) */
                limit?: number;
            };
            header?: never;
            path: {
                /** @description ID do produto */
                productId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Movimentações encontradas com sucesso. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Dados de requisição inválidos. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Token de acesso ausente ou inválido. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Sem permissão para listar movimentações. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Produto não encontrado. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MovementsController_registerMovement: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MovementDto"];
            };
        };
        responses: {
            /** @description Movimentação registrada com sucesso. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Dados inválidos ou divergência de saldo. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Token de acesso ausente ou inválido. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Sem permissão para registrar movimentações. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Produto não encontrado. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MovementsController_allocateLocation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AllocateLocationDto"];
            };
        };
        responses: {
            /** @description Alocação efetuada com sucesso. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Dados inválidos ou saldo insuficiente. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Token de acesso ausente ou inválido. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Sem permissão para alocar movimentações. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Produto ou localização não encontrada. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
